### ISSUE TITLE
Org level colors

### ISSUE THREAD

**Issue by inglada** [rails-to-cosmos/danneskjold-theme#3]
Hi,

I like your theme very much. Thank you.

However, I prefer colorful org headlines and you changed them to white! I have cloned your repo and reverted those changes, but I would like to use package.el and use-package as I do with most of the packages. 

Is there a way to customize these faces after having loaded the theme? I have not succeeded doing that. It seems that once the theme is loaded, the faces can't be changed.

I must be doing something wrong.

If you have any advice, I would be grateful.

Thanks.

**Comment by amirouche** [comment]
I am also interested in this feature.

**Comment by rails-to-cosmos** [comment]
Hi,

You can always customize any faces you want like that:
`(set-face-attribute 'org-level-1 nil :foreground "#FF0")`

I've changed org headlines to white and started using colorful todo-states:

```
(add-hook 'org-mode-hook
          (lambda ()
            (setq
             org-todo-keyword-faces
             '(("BLOCKED" . "#E74C3C")
               ("DEPLOY" . "#292")
               ("REVIEW" . "#292")
               ("CANCELLED" . "#7B9ED2")
               ("STARTED" . "#749AF7")
               ("PENDING" . "#D0E1F9")
               ("DELEGATED" . "#8B7FD7")
               ("CODE_REVIEW" . "#8B7FD7")
               ("FAILED" . "#E74C3C")
               ("PASSED" . "#4C3")
               ("TEST" . "#749AF7")))))
```

Thank you.

**Comment by inglada** [comment]
Thanks for the tip!
